import { notFound } from 'next/navigation';
import { readDb } from '@/lib/db';
import { BuyForm } from '@/components/buy-form';
import { createSupabasePublicClient } from '@/lib/supabase/server';
import { mapProduct, mapStore } from '@/lib/supabase/data';
import { useSupabase } from '@/lib/supabase/config';
import type { ProductRecord, StoreRecord } from '@/lib/types';
import { TrackingPixels } from '@/components/tracking-pixels';
export const dynamic = 'force-dynamic';

export default async function PublicStorePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  let store: StoreRecord | undefined; let products: ProductRecord[] = []; let pixel: any = {};
  if (useSupabase) {
    const client = createSupabasePublicClient();
    const { data: storeRow } = await client.from('stores').select('*').eq('slug', slug).eq('status', 'PUBLISHED').maybeSingle();
    if (storeRow) { const mappedStore = mapStore(storeRow); store = mappedStore; const { data: productRows } = await client.from('products').select('*').eq('store_id', mappedStore.id).eq('status', 'PUBLISHED').order('created_at', { ascending: true }); products = (productRows || []).map(mapProduct); const { data: settings } = await client.from('store_settings').select('seo_settings').eq('store_id', mappedStore.id).maybeSingle(); pixel = settings?.seo_settings?.pixel || {}; }
  } else {
    const db = await readDb(); const localStore = db.stores.find((item) => item.slug === slug && item.status === 'PUBLISHED'); store = localStore; products = localStore ? db.products.filter((item) => item.storeId === localStore.id && item.status === 'PUBLISHED') : [];
  }
  if (!store) notFound(); const publicStore = store as StoreRecord; const main = products[0];
  return <main className="min-h-screen"><TrackingPixels metaId={pixel.enabled?pixel.metaId:undefined} tiktokId={pixel.tiktokEnabled?pixel.tiktokId:undefined}/><div className="min-h-screen bg-[#fffdfa] text-ink"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><div className="flex items-center gap-2 font-black tracking-tight"><span style={{ backgroundColor: publicStore.primaryColor }} className="grid h-9 w-9 place-items-center rounded-xl text-sm text-white">{publicStore.name.slice(0, 1).toUpperCase()}</span><span>{publicStore.name}</span></div><a href="#catalogue" className="rounded-xl bg-ink px-4 py-2.5 text-sm font-extrabold text-white">Voir les produits</a></header>
    {!main ? <section className="mx-auto max-w-xl px-5 py-32 text-center"><h1 className="text-4xl font-black">La boutique arrive bientôt.</h1></section> : <><section className="border-y border-slate-100" style={{ background: `linear-gradient(115deg, ${publicStore.primaryColor}18, #fffdfa 55%)` }}><div className="mx-auto grid max-w-6xl gap-10 px-5 py-14 sm:px-8 lg:grid-cols-2 lg:items-center lg:py-24"><div><p className="text-sm font-black uppercase tracking-[.17em]" style={{ color: publicStore.primaryColor }}>Une sélection de {publicStore.name}</p><h1 className="mt-4 text-5xl font-black leading-[.95] tracking-[-.065em] sm:text-6xl">{publicStore.tagline}</h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600">Des produits choisis pour vous. Commandez simplement, puis réglez à la livraison.</p><a href="#catalogue" style={{ backgroundColor: publicStore.primaryColor }} className="mt-8 inline-block rounded-xl px-6 py-4 font-extrabold text-white shadow-lg">Découvrir le catalogue →</a></div><div className="grid min-h-80 place-items-center rounded-[2rem] bg-white p-6 shadow-float">{main.imageUrl ? <img src={main.imageUrl} alt={main.name} className="max-h-80 w-auto rounded-2xl object-contain" /> : <div className="grid h-64 w-full place-items-center rounded-2xl text-8xl" style={{ backgroundColor: `${publicStore.primaryColor}20` }}>✦</div>}</div></div></section>
      <section id="catalogue" className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><div className="mb-8 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-[.14em]" style={{ color: publicStore.primaryColor }}>Catalogue</p><h2 className="mt-2 text-3xl font-black tracking-[-.05em] sm:text-4xl">Nos produits</h2></div><p className="text-sm text-slate-500">{products.length} {products.length === 1 ? 'produit disponible' : 'produits disponibles'}</p></div><div className="grid gap-6 md:grid-cols-2">{products.map((product) => <article id={`produit-${product.id}`} key={product.id} className="scroll-mt-6 overflow-hidden rounded-[2rem] bg-white p-5 shadow-sm sm:p-7"><div className="grid min-h-64 place-items-center rounded-2xl" style={{ backgroundColor: `${publicStore.primaryColor}12` }}>{product.imageUrl ? <img src={product.imageUrl} alt={product.name} className="max-h-80 rounded-xl object-contain" /> : <span className="text-7xl">✦</span>}</div><div className="pt-6"><p className="text-sm font-black uppercase tracking-[.14em]" style={{ color: publicStore.primaryColor }}>Sélection {publicStore.name}</p><h3 className="mt-3 text-3xl font-black tracking-[-.045em]">{product.name}</h3><p className="mt-4 leading-7 text-slate-600">{product.description}</p><p className="mt-5 text-3xl font-black">{product.price.toLocaleString('fr-FR')} <span className="text-lg">{publicStore.currency}</span></p>{product.benefits.filter((benefit) => !/à compléter|à vérifier/i.test(benefit)).length > 0 && <ul className="mt-5 space-y-2 text-sm font-semibold text-slate-700">{product.benefits.filter((benefit) => !/à compléter|à vérifier/i.test(benefit)).map((benefit) => <li key={benefit}>✓ {benefit}</li>)}</ul>}<BuyForm storeSlug={publicStore.slug} product={product} currency={publicStore.currency} color={publicStore.primaryColor} /></div></article>)}</div></section>
      <section className="border-t border-slate-100 bg-white"><div className="mx-auto grid max-w-5xl gap-6 px-5 py-12 text-center sm:grid-cols-3 sm:px-8"><div><p className="font-black">Paiement à la livraison</p><p className="mt-2 text-sm text-slate-500">Payez lorsque votre commande arrive.</p></div><div><p className="font-black">Commande simple</p><p className="mt-2 text-sm text-slate-500">Vos coordonnées, puis confirmation du marchand.</p></div><div><p className="font-black">Besoin d’aide ?</p><p className="mt-2 text-sm text-slate-500">Contactez directement la boutique.</p></div></div></section></>}</div></main>;
}
