import { NextRequest } from 'next/server';
import { z } from 'zod';
import { currentUser } from '@/lib/auth';
import { mutateDb, slugify } from '@/lib/db';
import { apiError, assertSameOrigin } from '@/lib/security';
import { clientFor, fail, mapProduct } from '@/lib/supabase/data';
import { supabaseUrl, useSupabase } from '@/lib/supabase/config';

const updateSchema = z.object({ name: z.string().trim().min(2).max(140), description: z.string().trim().min(1).max(3000), price: z.number().finite().min(0).max(100000000), compareAtPrice: z.number().finite().min(0).max(100000000).nullable().optional(), stock: z.number().int().min(0).max(100000000).nullable().optional(), sku: z.string().trim().max(80).optional(), categoryName: z.string().trim().min(2).max(80).optional().or(z.literal('')), type: z.enum(['PHYSICAL', 'DIGITAL', 'SERVICE']).default('PHYSICAL'), status: z.enum(['DRAFT', 'PUBLISHED', 'ARCHIVED']), source: z.enum(['LINK', 'IMAGE', 'MANUAL']), sourceUrl: z.string().url().max(2048).optional(), benefits: z.array(z.string().trim().min(1).max(180)).max(6).default([]), imageUrl: z.string().max(2048).optional() });
function permittedImageUrl(url: string | undefined) { return !url || url.startsWith('/uploads/') || Boolean(supabaseUrl && url.startsWith(`${supabaseUrl}/storage/v1/object/public/store-assets/`)); }
async function supabaseCategory(client: ReturnType<typeof clientFor>, storeId: string, raw: string | undefined) { const name = raw?.trim(); if (!name) return null; const { data, error } = await client.from('categories').upsert({ store_id: storeId, name, slug: slugify(name) }, { onConflict: 'store_id,slug' }).select('id').single(); if (error) fail(error, 'Impossible d’enregistrer la catégorie.'); return data; }

export async function GET(_: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const user = await currentUser(); if (!user) throw new Error('Utilisateur non authentifié.'); const { id } = await params; if (useSupabase && user.accessToken) { const { data, error } = await clientFor(user).from('products').select('*,categories(name)').eq('id', id).single(); if (error) fail(error, 'Produit introuvable ou non autorisé.'); return Response.json({ product: mapProduct(data) }); } const db = await (await import('@/lib/db')).readDb(); const org = db.organizations.find((item) => item.userId === user.id); const store = org && db.stores.find((item) => item.organizationId === org.id); const product = db.products.find((item) => item.id === id && item.storeId === store?.id); if (!product) throw new Error('Produit introuvable ou non autorisé.'); return Response.json({ product: { ...product, categoryName: db.categories.find((item) => item.id === product.categoryId)?.name || product.categoryName } }); } catch (error) { return apiError(error); } }

export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { assertSameOrigin(request); const user = await currentUser(); if (!user) throw new Error('Utilisateur non authentifié.'); const { id } = await params; const input = updateSchema.parse(await request.json()); if (!permittedImageUrl(input.imageUrl)) throw new Error('Image non autorisée. Téléversez-la depuis Zelvora.'); if (input.compareAtPrice !== null && input.compareAtPrice !== undefined && input.compareAtPrice < input.price) throw new Error('Le prix comparé doit être supérieur ou égal au prix de vente.'); if (useSupabase && user.accessToken) { const client = clientFor(user); const { data: existing, error: existingError } = await client.from('products').select('store_id').eq('id', id).single(); if (existingError) fail(existingError, 'Produit introuvable ou non autorisé.'); const category = await supabaseCategory(client, existing.store_id, input.categoryName); const { data, error } = await client.from('products').update({ category_id: category?.id || null, name: input.name, description: input.description, price: input.price, compare_at_price: input.compareAtPrice ?? null, stock: input.stock ?? null, sku: input.sku || null, product_type: input.type, status: input.status, image_path: input.imageUrl || null, benefits: input.benefits, source_type: input.source, source_url: input.sourceUrl || null }).eq('id', id).select('*,categories(name)').single(); if (error) fail(error, 'Impossible de modifier ce produit.'); return Response.json({ product: mapProduct(data) }); } const product = await mutateDb((db) => { const org = db.organizations.find((item) => item.userId === user.id); const store = org && db.stores.find((item) => item.organizationId === org.id); const target = db.products.find((item) => item.id === id && item.storeId === store?.id); if (!target) throw new Error('Produit introuvable ou non autorisé.'); const name = input.categoryName?.trim(); let category = name ? db.categories.find((item) => item.storeId === target.storeId && item.slug === slugify(name)) : undefined; if (name && !category) { category = { id: crypto.randomUUID(), storeId: target.storeId, name, slug: slugify(name), createdAt: new Date().toISOString() }; db.categories.push(category); } Object.assign(target, { name: input.name, description: input.description, price: input.price, compareAtPrice: input.compareAtPrice ?? undefined, stock: input.stock ?? null, sku: input.sku || undefined, categoryId: category?.id, categoryName: category?.name, type: input.type, status: input.status, imageUrl: input.imageUrl, benefits: input.benefits, source: input.source, sourceUrl: input.sourceUrl }); return target; }); return Response.json({ product }); } catch (error) { return apiError(error); } }

export async function DELETE(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { assertSameOrigin(request); const user = await currentUser(); if (!user) throw new Error('Utilisateur non authentifié.'); const { id } = await params; if (useSupabase && user.accessToken) { const { error } = await clientFor(user).from('products').delete().eq('id', id); if (error) fail(error, 'Impossible de supprimer ce produit.'); return Response.json({ deleted: true }); } await mutateDb((db) => { const org = db.organizations.find((item) => item.userId === user.id); const store = org && db.stores.find((item) => item.organizationId === org.id); const index = db.products.findIndex((item) => item.id === id && item.storeId === store?.id); if (index < 0) throw new Error('Produit introuvable ou non autorisé.'); db.products.splice(index, 1); }); return Response.json({ deleted: true }); } catch (error) { return apiError(error); } }
