import Link from 'next/link';
import { Logo } from '@/components/logo';

const featureCards = [
  { icon: '✦', title: 'Import intelligent', text: 'Par lien, image ou saisie guidée.' },
  { icon: '◌', title: 'Mobile dès le départ', text: 'Pensé pour les écrans de vos clients.' },
  { icon: '↗', title: 'Contenu sous contrôle', text: 'Chaque proposition reste modifiable.' }
];

const steps = [
  ['01', 'Apportez votre produit', 'Un lien, une image ou quelques informations suffisent pour démarrer.'],
  ['02', 'Donnez une direction', 'Choisissez un univers, vérifiez les contenus et ajustez votre boutique.'],
  ['03', 'Publiez et pilotez', 'Recevez des commandes, confirmez-les et développez votre activité.']
];

function ProductArtwork() {
  return <div className="relative grid h-full min-h-48 place-items-center overflow-hidden rounded-xl bg-[#EEE8FF] sm:min-h-64"><span className="absolute -right-12 -top-10 h-36 w-36 rounded-full bg-[#D5CAFF]" /><span className="absolute -bottom-12 -left-10 h-32 w-32 rounded-full bg-[#FFD9B2]" /><div className="relative h-28 w-28 sm:h-36 sm:w-36"><div className="absolute inset-x-5 bottom-0 h-24 rounded-[1.8rem] border-[5px] border-[#20273E] bg-[#7D62EA] shadow-[0_14px_18px_rgba(42,34,89,.24)] sm:h-32"><div className="absolute left-1/2 top-4 h-10 w-10 -translate-x-1/2 rounded-full border-[4px] border-[#20273E] bg-[#FFF6D9] sm:h-14 sm:w-14" /><div className="absolute bottom-4 left-1/2 h-2 w-10 -translate-x-1/2 rounded-full bg-[#20273E]" /></div><span className="absolute left-1/2 top-0 h-8 w-10 -translate-x-1/2 rounded-t-full border-x-[5px] border-t-[5px] border-[#20273E]" /></div><p className="absolute bottom-3 rounded-full bg-white/75 px-2 py-1 text-[7px] font-black tracking-[.12em] text-[#44369E]">LUMIÈRE NOMADE</p></div>;
}

function StudioPreview() {
  const builderSections = ['Visuel principal', 'Bénéfices essentiels', 'Réassurance & FAQ', 'Détails à vérifier'];
  return <div className="relative mx-auto w-full max-w-[700px] rounded-[1.8rem] border border-slate-200 bg-white p-2 shadow-[0_30px_90px_rgba(31,36,61,.17)] sm:p-3">
    <div className="overflow-hidden rounded-[1.35rem] border border-slate-100 bg-[#FAFBFE]">
      <div className="flex items-center justify-between border-b border-slate-100 bg-white px-3 py-2.5 sm:px-4"><div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-lg bg-violet text-[10px] font-black text-white">Z</span><p className="text-[10px] font-black sm:text-xs">Atelier Zelvora</p></div><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-mint ring-2 ring-mint/30" /><span className="text-[9px] font-bold text-slate-400">Brouillon sauvegardé</span></div></div>
      <div className="flex items-center gap-1 overflow-x-auto border-b border-slate-100 bg-white px-3 py-2.5 text-[9px] font-black sm:justify-center sm:gap-2 sm:text-[10px]"><span className="shrink-0 rounded-full border border-slate-200 px-2.5 py-1.5 text-slate-500">1 · Importer</span><span className="text-slate-300">→</span><span className="shrink-0 rounded-full border border-slate-200 px-2.5 py-1.5 text-slate-500">2 · Composer</span><span className="text-slate-300">→</span><span className="shrink-0 rounded-full bg-violet px-2.5 py-1.5 text-white">3 · Personnaliser</span><span className="text-slate-300">→</span><span className="shrink-0 rounded-full border border-slate-200 px-2.5 py-1.5 text-slate-500">Publier</span></div>
      <div className="grid min-h-[360px] sm:grid-cols-[.7fr_1.3fr]">
        <aside className="hidden border-r border-slate-100 bg-white p-3 sm:block"><p className="text-[9px] font-black uppercase tracking-[.14em] text-slate-400">Section active</p><div className="mt-3 space-y-1.5">{builderSections.map((item, index) => <div key={item} className={`rounded-lg border px-2.5 py-2 text-[9px] font-bold ${index === 0 ? 'border-violet/30 bg-violet/5 text-violet' : 'border-slate-100 text-slate-500'}`}><span className="mr-1 text-slate-400">{index + 1}.</span>{item}</div>)}</div><div className="mt-4 rounded-lg bg-[#F5F4FB] p-2.5"><p className="text-[9px] font-black text-ink">Contrôle marchand</p><p className="mt-1 text-[9px] leading-4 text-slate-500">Les informations non confirmées restent signalées.</p></div></aside>
        <div className="p-3 sm:p-4"><div className="mb-2.5 flex items-center justify-between"><p className="text-[9px] font-black text-slate-500">Prévisualisation</p><span className="rounded-md bg-slate-100 px-2 py-1 text-[8px] font-black text-slate-500">MOBILE</span></div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-3 py-2 text-[8px] font-black"><span className="flex items-center gap-1.5"><i className="h-3 w-3 rounded bg-[#FFD277]" /> Kalo &amp; Co</span><span className="text-slate-400">Accueil&nbsp; · &nbsp;Panier</span></div><div className="grid grid-cols-[.88fr_1.12fr] gap-2.5 bg-[#FFFCF5] p-3 sm:gap-4 sm:p-4"><ProductArtwork /><div className="py-1"><p className="text-[7px] font-black uppercase tracking-[.16em] text-violet">Nouveau départ</p><h2 className="mt-2 text-base font-black leading-[.93] tracking-[-.06em] sm:text-xl">Une lumière qui vous accompagne.</h2><p className="mt-2 line-clamp-3 text-[8px] leading-3 text-slate-500 sm:text-[9px] sm:leading-4">Une pièce compacte à découvrir et à adapter à votre quotidien.</p><p className="mt-3 text-xs font-black sm:text-sm">18 500 <span className="text-[8px]">FCFA</span></p><div className="mt-2 space-y-1 text-[7px] font-bold text-slate-500"><p>✓ Simple à utiliser</p><p>✓ Format pratique</p></div><div className="mt-3 rounded-lg bg-violet px-2 py-2 text-center text-[8px] font-black text-white">COMMANDER</div></div></div></div><div className="mt-3 rounded-xl border border-slate-100 bg-white p-2.5"><div className="flex items-center justify-between"><p className="text-[9px] font-black">Boutiques récentes</p><span className="text-[8px] font-bold text-violet">Explorer</span></div><div className="mt-2 grid grid-cols-3 gap-2"><span className="h-9 rounded-md bg-[#F1D7C0]" /><span className="h-9 rounded-md bg-[#D9E5FF]" /><span className="h-9 rounded-md bg-[#D7F0E3]" /></div></div></div>
      </div>
    </div>
  </div>;
}

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#F6F7FA] text-ink">
    <header className="relative z-20 mx-auto mt-5 flex max-w-6xl items-center justify-between rounded-full border border-white/80 bg-white/90 px-5 py-3 shadow-[0_12px_50px_rgba(15,23,42,.08)] backdrop-blur sm:px-7"><Logo /><nav className="hidden items-center gap-8 text-sm font-bold text-slate-600 md:flex"><a href="#fonctionnement" className="hover:text-violet">Comment ça marche</a><a href="#zelvora" className="hover:text-violet">Pourquoi Zelvora</a></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden px-4 py-2 text-sm font-extrabold sm:block">Connexion →</Link><Link href="/register" className="rounded-full bg-[#101114] px-5 py-3 text-sm font-extrabold text-white shadow-lg">Inscription</Link></div></header>

    <section className="relative flex min-h-[650px] items-center border-b border-slate-200 px-5 pb-20 pt-24 text-center sm:px-8"><div aria-hidden className="absolute inset-0 grid-dots opacity-20" /><div aria-hidden className="absolute left-1/2 top-1/3 h-80 w-80 -translate-x-1/2 rounded-full bg-blue-400/10 blur-3xl" /><div className="relative mx-auto max-w-5xl"><div className="mx-auto inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-2 py-1.5 pr-4 text-sm font-bold shadow-sm"><span className="rounded-full bg-blue-600 px-3 py-1 text-white">Créé pour l’Afrique</span><span className="text-slate-700">Un outil e-commerce complet</span></div><h1 className="mt-9 text-5xl font-black leading-[1.02] tracking-[-.065em] text-[#111214] sm:text-6xl lg:text-7xl">Crée ta boutique e-commerce<br className="hidden md:block" /> <span className="bg-gradient-to-r from-blue-600 via-violet to-fuchsia-500 bg-clip-text text-transparent">avec l’IA en quelques minutes</span></h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-600 sm:text-xl">Ajoute simplement ton produit. Zelvora t’aide à créer ta fiche produit, tes contenus et une boutique professionnelle, optimisée pour mobile.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="rounded-full bg-[#151619] px-9 py-4 font-extrabold text-white shadow-[0_15px_35px_rgba(0,0,0,.22)] transition hover:-translate-y-1">Créer ma boutique gratuitement →</Link><a href="#fonctionnement" className="rounded-full border border-slate-300 bg-white px-9 py-4 font-extrabold transition hover:border-violet hover:text-violet">Découvrir Zelvora</a></div><p className="mt-5 text-sm font-semibold text-slate-500">Aucune compétence technique requise · Paiement à la livraison · Mobile-first</p><div className="mx-auto mt-14 max-w-4xl"><StudioPreview /></div></div></section>

    <section id="fonctionnement" className="border-y border-slate-200 bg-white py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="grid gap-8 lg:grid-cols-[.82fr_1.18fr] lg:items-end"><div><p className="text-sm font-black uppercase tracking-[.18em] text-violet">Un parcours clair</p><h2 className="mt-3 text-4xl font-black leading-[.98] tracking-[-.06em] sm:text-5xl">De l’idée à la<br />première commande.</h2></div><p className="max-w-xl text-lg leading-8 text-slate-600">Pas besoin d’être développeur. Zelvora vous accompagne de la fiche produit à la publication, tout en vous laissant vérifier chaque élément important.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{steps.map(([number, title, text]) => <article key={number} className="rounded-2xl bg-[#F7F7FB] p-6"><p className="text-sm font-black text-violet">{number}</p><h3 className="mt-10 text-xl font-black tracking-tight">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

    <section id="zelvora" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-24"><div className="rounded-[2rem] bg-ink px-7 py-12 text-white sm:px-12 sm:py-14"><div className="grid gap-10 lg:grid-cols-2 lg:items-end"><div><p className="text-sm font-black uppercase tracking-[.18em] text-mint">Une IA responsable</p><h2 className="mt-4 text-4xl font-black leading-[.96] tracking-[-.06em] sm:text-5xl">Zelvora propose.<br />Vous gardez la main.</h2></div><p className="max-w-xl text-lg leading-8 text-slate-300">Chaque suggestion peut être modifiée ou refusée. Quand une information commerciale manque, Zelvora vous l’indique au lieu de la présenter comme certaine.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-5"><p className="text-2xl text-mint">✦</p><p className="mt-4 font-extrabold">Boutique mobile</p><p className="mt-2 text-sm leading-6 text-slate-300">Une expérience lisible sur le téléphone de vos clients.</p></div><div className="rounded-2xl bg-white/10 p-5"><p className="text-2xl text-mint">◌</p><p className="mt-4 font-extrabold">Commandes réelles</p><p className="mt-2 text-sm leading-6 text-slate-300">Un checkout COD relié à votre tableau de bord.</p></div><div className="rounded-2xl bg-white/10 p-5"><p className="text-2xl text-mint">↗</p><p className="mt-4 font-extrabold">Marque personnelle</p><p className="mt-2 text-sm leading-6 text-slate-300">Partagez votre boutique sur vos réseaux et WhatsApp.</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="rounded-[2rem] border border-violet/15 bg-violet/[.05] px-7 py-12 text-center sm:px-12"><p className="text-sm font-black uppercase tracking-[.18em] text-violet">Votre premier pas</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-black leading-[.98] tracking-[-.06em] sm:text-5xl">Votre prochaine boutique commence par un produit.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-slate-600">Importez-le, ajustez votre page et publiez quand les informations vous conviennent.</p><Link href="/register" className="mt-8 inline-block rounded-xl bg-violet px-6 py-4 font-extrabold text-white shadow-lg shadow-violet/25">Créer ma boutique gratuitement →</Link></div></section>

    <footer className="border-t border-slate-200 px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-sm font-medium text-slate-500 sm:flex-row"><Logo /><span>© {new Date().getFullYear()} Zelvora · Du produit à la boutique.</span></div></footer>
  </main>;
}
