import Link from 'next/link';
import Image from 'next/image';
import { Logo } from '@/components/logo';

const features=[
 ['✦','Création assistée par IA','Transformez un lien, une photo ou vos informations en une fiche produit modifiable.'],
 ['▣','Boutique mobile-first','Une vitrine rapide et lisible, pensée pour les clients qui commandent sur smartphone.'],
 ['⌁','Commandes centralisées','Recevez vos commandes et suivez chaque statut depuis un tableau de bord simple.']
];
const faqs=[
 ['À quoi sert Zelvora ?','Zelvora aide les e-commerçants à créer une boutique, présenter leurs produits et gérer leurs commandes sans savoir coder.'],
 ["Puis-je tester avant de m’abonner ?","Vous pouvez créer votre compte et préparer votre boutique. La publication dépend ensuite d’un abonnement actif."],
 ['Quels moyens de paiement sont prévus ?','Les paiements manuels prévus sont MyNita, Amanata, Airtel Money et Wave. La validation est effectuée après contrôle de la preuve.'],
 ['Combien de temps faut-il pour créer une boutique ?','Le premier brouillon peut être préparé rapidement. Vous gardez toujours la main pour vérifier les textes, prix et images avant publication.'],
 ['Est-ce adapté au téléphone ?','Oui. Le dashboard et les boutiques sont conçus en priorité pour les smartphones, puis adaptés aux tablettes et ordinateurs.'],
 ['Les contenus IA sont-ils modifiables ?','Oui. Les suggestions IA restent modifiables et les informations non vérifiées sont clairement signalées.']
];
function BuilderVisual(){return <div className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white shadow-[0_24px_70px_rgba(15,23,42,.12)]"><div className="flex items-center justify-between border-b px-4 py-3 text-xs font-black"><span className="flex items-center gap-2"><i className="grid h-7 w-7 place-items-center rounded-lg bg-blue-600 not-italic text-white">Z</i>Atelier Zelvora</span><span className="rounded-full bg-green-100 px-3 py-1 text-green-700">Brouillon sauvegardé</span></div><div className="flex gap-2 overflow-x-auto border-b p-3 text-[10px] font-black"><span className="rounded-full border px-3 py-1">1. Importer</span><span className="rounded-full border px-3 py-1">2. Sélectionner</span><span className="rounded-full bg-blue-600 px-3 py-1 text-white">3. Personnaliser</span><span className="rounded-full border px-3 py-1">4. Publier</span></div><div className="grid min-h-[390px] grid-cols-[.65fr_1.35fr]"><aside className="border-r bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Sections</p>{['Visuel produit','Avantages clés','Garantie & FAQ','Détails'].map((x,i)=><div key={x} className={`mt-3 rounded-lg border p-3 text-xs font-bold ${i===0?'border-blue-300 bg-blue-50 text-blue-700':'bg-white text-slate-500'}`}>{i+1}. {x}</div>)}</aside><div className="p-4"><div className="mb-3 flex justify-between text-[10px] font-black text-slate-500"><span>APERÇU DE LA BOUTIQUE</span><span>Mobile · Desktop</span></div><div className="overflow-hidden rounded-xl border bg-white"><div className="h-5 bg-blue-600"/><div className="grid grid-cols-2 gap-4 p-4"><div className="relative min-h-52 overflow-hidden rounded-xl bg-amber-50"><Image src="/images/store-product.jpg" alt="Exemple de photographie produit professionnelle" fill className="object-cover" sizes="320px"/></div><div><span className="text-[9px] font-black text-blue-600">NOUVEAUTÉ</span><h3 className="mt-2 text-xl font-black leading-tight">Votre produit, bien présenté.</h3><p className="mt-3 text-[10px] leading-5 text-slate-500">Une page claire avec bénéfices, détails, prix et appel à l’action.</p><p className="mt-4 font-black">15 000 FCFA</p><button className="mt-4 w-full rounded-lg bg-blue-600 py-3 text-[10px] font-black text-white">COMMANDER MAINTENANT</button></div></div></div></div></div></div>}
function ExploreVisual(){return <div className="relative min-h-[350px] overflow-hidden rounded-[1.6rem] bg-blue-50"><Image src="/images/product-explorer.jpg" alt="Sélection de produits pour trouver une idée e-commerce" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw"/><div className="absolute left-5 top-5 rounded-xl bg-white/95 p-4 text-xs font-black shadow-xl backdrop-blur">Explorer des produits<br/><span className="font-medium text-slate-500">Sources vérifiées uniquement</span></div><div className="absolute bottom-7 right-5 rounded-xl bg-blue-600 px-5 py-3 text-xs font-black text-white shadow-xl">Filtrer les opportunités</div></div>}
function ImportVisual(){return <div className="relative min-h-[350px] overflow-hidden rounded-[1.6rem] bg-slate-100"><Image src="/images/african-entrepreneurs.jpg" alt="Entrepreneurs africains créant une boutique en ligne" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw"/><div className="absolute inset-x-5 bottom-5 rounded-2xl bg-white/95 p-4 shadow-xl backdrop-blur"><p className="text-xs font-black text-blue-600">IMPORTATION INTELLIGENTE</p><p className="mt-1 text-sm font-bold">Un lien ou une photo devient une fiche produit modifiable.</p></div></div>}
export default function Home(){return <main className="overflow-hidden bg-[#f6f6f7] text-[#111214]">
<header className="sticky top-4 z-30 mx-auto mt-4 flex max-w-6xl items-center justify-between rounded-full border border-white bg-white/95 px-5 py-3 shadow-[0_10px_45px_rgba(0,0,0,.08)] backdrop-blur sm:px-8"><Logo/><nav className="hidden gap-7 text-sm font-bold text-slate-600 lg:flex"><a href="#fonctionnalites">Fonctionnalités</a><a href="#tarifs">Tarifs</a><a href="#faq">FAQ</a></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden px-4 py-2 text-sm font-extrabold sm:block">Connexion →</Link><Link href="/register" className="rounded-full bg-black px-5 py-3 text-sm font-extrabold text-white">Inscription</Link></div></header>
<section className="relative flex min-h-[680px] items-center px-5 py-24 text-center"><div className="absolute inset-0 grid-dots opacity-20"/><div className="relative mx-auto max-w-5xl"><div className="inline-flex items-center rounded-full border bg-white p-1 pr-4 text-sm font-bold shadow-sm"><span className="mr-2 rounded-full bg-blue-600 px-3 py-1 text-white">Pensé pour l’Afrique</span>Un outil e-commerce complet</div><h1 className="mt-9 text-5xl font-black leading-[1] tracking-[-.07em] sm:text-6xl lg:text-7xl">Lance ta boutique e-commerce<br/><span className="bg-gradient-to-r from-blue-600 via-violet to-fuchsia-500 bg-clip-text text-transparent">avec l’IA en quelques minutes</span></h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-600">Ajoute ton produit par lien, image ou saisie manuelle. Zelvora t’aide à créer tes contenus, ta boutique mobile et à recevoir tes commandes.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="rounded-full bg-black px-9 py-4 font-extrabold text-white shadow-[0_18px_35px_rgba(0,0,0,.22)]">Créer ma boutique gratuitement →</Link><a href="#fonctionnalites" className="rounded-full border bg-white px-9 py-4 font-extrabold">Découvrir Zelvora</a></div><p className="mt-5 text-sm font-semibold text-slate-500">Sans compétence technique · Mobile-first · Contenus modifiables</p></div></section>
<section id="fonctionnalites" className="border-y bg-white px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="font-black uppercase tracking-[.18em] text-blue-600">CRÉATION INTELLIGENTE</p><h2 className="mt-4 text-5xl font-black leading-[1.02] tracking-[-.06em]">Crée des boutiques e-commerce <span className="text-blue-600">avec l’IA</span></h2><p className="mt-6 text-lg leading-8 text-slate-600">Prépare rapidement une boutique professionnelle, prête à présenter tes produits et convertir tes visiteurs.</p><div className="mt-10 grid gap-3 sm:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3">{features.map(f=><article key={f[1]} className="rounded-2xl border bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white">{f[0]}</span><h3 className="mt-5 font-black">{f[1]}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{f[2]}</p></article>)}</div><Link href="/register" className="mt-8 inline-block rounded-full bg-black px-8 py-4 font-extrabold text-white shadow-xl">Commencer →</Link></div><BuilderVisual/></div></section>
<section className="px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2"><article className="rounded-[2rem] border bg-white p-7 shadow-sm"><ExploreVisual/><h2 className="mt-8 text-2xl font-black">Pas encore d’idée de produit ?</h2><p className="mt-3 text-lg leading-8 text-slate-600">Explore des opportunités lorsque des sources vérifiées sont connectées. Zelvora n’invente pas de fausses tendances.</p></article><article className="rounded-[2rem] border bg-white p-7 shadow-sm"><ImportVisual/><h2 className="mt-8 text-2xl font-black">Importation intelligente</h2><p className="mt-3 text-lg leading-8 text-slate-600">Transforme un lien produit, une photo ou tes informations en boutique complète, puis vérifie tout avant de publier.</p></article></div></section>
<section id="tarifs" className="border-y bg-white px-5 py-24 text-center sm:px-8"><p className="font-black uppercase tracking-[.18em] text-blue-600">ABONNEMENTS</p><h2 className="mt-4 text-5xl font-black tracking-[-.06em]">Des tarifs <span className="text-blue-600">simples</span></h2><p className="mt-5 text-lg text-slate-600">Choisis la formule adaptée à ton activité.</p><div className="mx-auto mt-12 grid max-w-4xl gap-5 md:grid-cols-2"><article className="rounded-[2rem] border bg-[#f7f7f8] p-8 text-left"><span className="text-sm font-black text-blue-600">PRO</span><p className="mt-4 text-4xl font-black">15 000 <small className="text-base">FCFA/mois</small></p><ul className="mt-7 space-y-3 text-slate-600"><li>✓ Boutique professionnelle</li><li>✓ Gestion produits et commandes</li><li>✓ Assistance IA selon les limites du plan</li></ul><Link href="/register" className="mt-8 block rounded-full bg-black py-4 text-center font-extrabold text-white">Choisir PRO</Link></article><article className="rounded-[2rem] bg-[#0d111c] p-8 text-left text-white shadow-2xl"><span className="rounded-full bg-blue-600 px-3 py-1 text-sm font-black">BUSINESS</span><p className="mt-4 text-4xl font-black">30 000 <small className="text-base text-slate-400">FCFA/mois</small></p><ul className="mt-7 space-y-3 text-slate-300"><li>✓ Capacités supérieures</li><li>✓ Fonctionnalités avancées</li><li>✓ Accompagnement prioritaire</li></ul><Link href="/register" className="mt-8 block rounded-full bg-white py-4 text-center font-extrabold text-black">Choisir BUSINESS</Link></article></div><p className="mt-7 text-sm text-slate-500">Paiements manuels : MyNita · Amanata · Airtel Money · Wave</p></section>
<section id="faq" className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-7xl"><p className="font-black uppercase tracking-[.18em] text-blue-600">FAQ</p><h2 className="mt-4 text-5xl font-black tracking-[-.06em]">Tes questions. Nos réponses.</h2><div className="mt-12 grid gap-4 md:grid-cols-2">{faqs.map(([q,a])=><details key={q} className="group rounded-2xl border bg-white p-6 shadow-sm" open><summary className="cursor-pointer list-none pr-8 text-lg font-black">{q}<span className="float-right grid h-8 w-8 place-items-center rounded-full bg-black text-white group-open:rotate-45">+</span></summary><p className="mt-5 border-t pt-5 leading-7 text-slate-600">{a}</p></details>)}</div></div></section>
<section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-7xl rounded-[2.5rem] bg-gradient-to-br from-blue-600 to-violet px-7 py-16 text-center text-white"><h2 className="text-4xl font-black tracking-[-.05em] sm:text-5xl">Prêt à lancer ta boutique ?</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-blue-100">Crée ton compte, ajoute ton produit et prépare une boutique professionnelle.</p><Link href="/register" className="mt-8 inline-block rounded-full bg-white px-9 py-4 font-extrabold text-black">Commencer gratuitement →</Link></div></section>
<footer className="border-t bg-white px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 sm:flex-row"><Logo/><p className="text-sm text-slate-500">© {new Date().getFullYear()} Zelvora · E-commerce simplifié.</p></div></footer>
</main>}
