'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Data = any;
const money = (value: number, currency = 'XOF') => `${Math.round(value).toLocaleString('fr-FR')} ${currency}`;
export function DashboardClient() {
  const router = useRouter(); const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(''); const [publishing, setPublishing] = useState(false);
  const refresh = () => fetch('/api/dashboard').then(async (response) => { const json = await response.json(); if (!response.ok) throw new Error(json.error); return json; }).then(setData).catch((e) => setError(e.message));
  useEffect(() => { refresh(); }, []);
  async function publish() { if (!data?.store) return; setPublishing(true); const res = await fetch(`/api/stores/${data.store.id}/publish`, { method: 'POST' }); const json = await res.json(); setPublishing(false); if (!res.ok) { setError(json.error); return; } refresh(); router.refresh(); }
  if (error) return <div className="rounded-2xl bg-red-50 p-5 font-bold text-red-700">{error}</div>;
  if (!data) return <div className="animate-pulse rounded-2xl bg-slate-200 p-16 text-slate-400">Chargement de votre espace…</div>;
  if (!data.store) return <div className="rounded-[2rem] bg-ink p-8 text-white sm:p-12"><p className="text-mint">Votre prochaine étape</p><h1 className="mt-3 text-4xl font-black tracking-[-.055em]">Créons votre première boutique.</h1><p className="mt-4 max-w-xl leading-7 text-slate-300">Ajoutez votre produit : Zelvora vous guide du lien, de l’image ou des informations saisies jusqu’à la boutique.</p><Link href="/onboarding" className="mt-7 inline-block rounded-xl bg-white px-5 py-3 font-extrabold text-ink">Créer ma boutique →</Link></div>;
  const cards = [['Chiffre d’affaires', money(data.metrics.revenue, data.store.currency), 'Commandes hors annulation'], ['Commandes', data.metrics.orders, 'Depuis la publication'], ['Clients', data.metrics.customers, 'Fiches clients créées'], ['Panier moyen', money(data.metrics.averageOrder, data.store.currency), 'Par commande']];
  return <><section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-[.16em] text-violet">Vue d’ensemble</p><h1 className="mt-2 text-3xl font-black tracking-[-.055em] sm:text-4xl">Bonjour {data.user.name.split(' ')[0]} 👋</h1><p className="mt-2 text-slate-600">Voici ce qui se passe dans <strong>{data.store.name}</strong>.</p></div><div className="flex gap-3"><Link href={`/store/${data.store.slug}`} target="_blank" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-extrabold">Voir la boutique ↗</Link>{data.store.status !== 'PUBLISHED' && <button onClick={publish} disabled={publishing} className="rounded-xl bg-violet px-4 py-3 text-sm font-extrabold text-white">{publishing ? 'Publication…' : 'Publier'}</button>}</div></section>{data.store.status !== 'PUBLISHED' && <section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="font-extrabold text-amber-900">Votre boutique est en brouillon.</p><p className="mt-1 text-sm text-amber-800">Vérifiez vos informations produit, puis publiez-la pour accepter des commandes.</p></section>}
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,detail]) => <article key={label as string} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-4 text-2xl font-black tracking-[-.04em]">{value}</p><p className="mt-2 text-xs font-semibold text-slate-400">{detail}</p></article>)}</section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Commandes récentes</h2><p className="mt-1 text-sm text-slate-500">Suivez et confirmez vos commandes.</p></div><Link href="/orders" className="text-sm font-extrabold text-violet">Voir tout →</Link></div>{data.orders.length ? <div className="mt-5 divide-y divide-slate-100">{data.orders.map((order: any) => <div key={order.id} className="flex items-center justify-between gap-3 py-4"><div><p className="font-extrabold">{order.number} <span className="font-medium text-slate-500">· {order.productName}</span></p><p className="mt-1 text-xs font-semibold text-slate-500">{new Date(order.createdAt).toLocaleDateString('fr-FR')}</p></div><div className="text-right"><p className="font-black">{money(order.total, order.currency)}</p><p className="mt-1 text-xs font-black uppercase text-violet">{order.status}</p></div></div>)}</div> : <div className="mt-5 rounded-xl bg-surface p-6 text-center text-sm leading-6 text-slate-600">Vos prochaines commandes apparaîtront ici.<br />Partagez l’URL de votre boutique sur WhatsApp ou vos réseaux.</div>}</article><aside className="space-y-6"><article className="rounded-2xl bg-ink p-5 text-white"><p className="text-sm font-bold text-mint">ZELVORA AI</p><p className="mt-3 text-xl font-black tracking-tight">Crédits IA : {data.aiCredits.used} / {data.aiCredits.limit}</p><p className="mt-2 text-sm leading-6 text-slate-300">Le provider AI est en mode démo dans cette fondation. Les suggestions restent à vérifier.</p></article><article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="font-black">Notifications</h2>{data.notifications.length ? <div className="mt-4 space-y-3">{data.notifications.map((n: any) => <div key={n.id} className="rounded-xl bg-surface p-3"><p className="text-sm font-extrabold">🔔 {n.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{n.body}</p></div>)}</div> : <p className="mt-4 text-sm text-slate-500">Aucune nouvelle notification.</p>}</article></aside></section></>;
}
