import Link from 'next/link';
import { ReactNode } from 'react';
import { Logo } from '@/components/logo';
import { PwaNotifications } from '@/components/pwa-notifications';
import { currentUser } from '@/lib/auth';
import { clientFor } from '@/lib/supabase/data';

export type Workspace = 'dashboard'|'orders'|'products'|'clients'|'marketing'|'studio'|'analysis'|'explore'|'notifications'|'subscription'|'settings';
type NavItem={id:Workspace;label:string;href:string;icon:string};
const groups:Array<{label:string;items:NavItem[]}>= [
 {label:'Business',items:[{id:'dashboard',label:'Tableau de bord',href:'/dashboard',icon:'▦'},{id:'orders',label:'Commandes',href:'/orders',icon:'□'},{id:'products',label:'Produits',href:'/products',icon:'◇'},{id:'clients',label:'Clients',href:'/clients',icon:'♙'}]},
 {label:'Outils',items:[{id:'marketing',label:'Marketing',href:'/marketing',icon:'◇'},{id:'studio',label:'Ma boutique',href:'/studio',icon:'⌂'},{id:'analysis',label:'Créer avec IA',href:'/analysis',icon:'✦'},{id:'explore',label:'Explorer',href:'/explore',icon:'⌕'}]},
 {label:'Compte',items:[{id:'notifications',label:'Notifications',href:'/notifications',icon:'●'},{id:'subscription',label:'Abonnement',href:'/subscription',icon:'◆'},{id:'settings',label:'Paramètres',href:'/settings',icon:'⚙'}]}
];
function Navigation({active,compact=false}:{active:Workspace;compact?:boolean}){const all=groups.flatMap(g=>g.items);if(compact)return <nav aria-label="Navigation mobile" className="flex gap-1 overflow-x-auto px-4 py-2">{all.map(e=><Link key={e.id} href={e.href} aria-current={active===e.id?'page':undefined} className={`shrink-0 rounded-lg px-3 py-2 text-xs font-extrabold ${active===e.id?'bg-white/12 text-white':'text-slate-400'}`}>{e.label}</Link>)}</nav>;return <nav className="mt-7 flex-1 overflow-y-auto" aria-label="Navigation principale">{groups.map(g=><section key={g.label} className="mb-5"><p className="px-3 pb-2 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">{g.label}</p><div className="space-y-1">{g.items.map(e=><Link key={e.id} href={e.href} aria-current={active===e.id?'page':undefined} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-extrabold transition ${active===e.id?'bg-white/12 text-white shadow-sm':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><span className={`grid h-5 w-5 place-items-center ${active===e.id?'text-mint':'text-slate-500'}`}>{e.icon}</span>{e.label}</Link>)}</div></section>)}</nav>}
export async function MerchantShell({active,children}:{active:Workspace;children:ReactNode}){let isAdmin=false;const user=await currentUser();if(user?.accessToken){const{data}=await clientFor(user).from('profiles').select('is_platform_admin,status').eq('id',user.id).maybeSingle();isAdmin=Boolean(data?.is_platform_admin&&data?.status==='ACTIVE')}return <main className="merchant-dark min-h-screen"><PwaNotifications/><div className="min-h-screen bg-[#050b18] text-slate-100"><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 flex-col border-r border-white/10 bg-[#020817] p-5 lg:flex"><Logo href="/dashboard" light/><Navigation active={active}/>{isAdmin&&<Link href="/admin" className="mb-5 block rounded-xl border border-violet/40 bg-violet/15 px-4 py-3 text-sm font-extrabold text-violet-200">Administration Zelvora</Link>}<div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="text-xs font-black text-mint">ZELVORA V1</p><p className="mt-2 text-xs font-bold leading-5 text-slate-300">Vos données restent privées à votre organisation.</p></div></aside><div className="min-h-screen lg:pl-64"><header className="sticky top-0 z-10 border-b border-white/10 bg-[#0B1120] text-white"><div className="flex h-16 items-center justify-between px-4 sm:px-6 lg:px-8"><div className="lg:hidden"><Logo href="/dashboard" light/></div><p className="hidden text-sm font-bold text-slate-400 lg:block">Espace marchand</p><div className="flex items-center gap-3">{isAdmin&&<Link href="/admin" className="rounded-lg bg-violet px-3 py-2 text-xs font-black text-white">Administration</Link>}<Link href="/notifications" className="text-slate-400" aria-label="Notifications">●</Link><Link href="/settings" className="grid h-8 w-8 place-items-center rounded-full bg-violet text-xs font-black">Z</Link></div></div><div className="border-t border-white/10 lg:hidden"><Navigation active={active} compact/></div></header><div className="mx-auto max-w-7xl px-5 py-7 sm:px-8 sm:py-9">{children}</div></div></div></main>}
