'use client';
import Link from 'next/link'; import { useEffect, useState } from 'react'; import { useRouter } from 'next/navigation';
const statuses = ['NEW','CONFIRMED','PREPARING','SHIPPED','DELIVERED','CANCELLED','RETURNED'];
const labels: Record<string,string> = { NEW:'Nouvelle', CONFIRMED:'Confirmée', PREPARING:'En préparation', SHIPPED:'Expédiée', DELIVERED:'Livrée', CANCELLED:'Annulée', RETURNED:'Retournée' };
export function OrdersClient() { const router = useRouter(); const [orders,setOrders]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=()=>fetch('/api/orders').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d.orders;}).then(setOrders).catch(e=>setError(e.message)).finally(()=>setLoading(false)); useEffect(()=>{load()},[]);
  async function change(id:string,status:string){ const r=await fetch('/api/orders',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})}); const d=await r.json();if(!r.ok){setError(d.error);return} setOrders(prev=>prev.map(o=>o.id===id?d.order:o)); }
  if (error) return <div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>; if(loading)return <p className="text-slate-500">Chargement des commandes…</p>;
  return <><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.16em] text-violet">Ventes</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em]">Commandes</h1><p className="mt-2 text-slate-600">Mettez à jour vos commandes à chaque étape.</p></div><Link href="/dashboard" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-extrabold">← Tableau de bord</Link></div><div className="mt-7 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm">{orders.length?<div className="divide-y divide-slate-100">{orders.map(o=><article key={o.id} className="grid gap-4 p-5 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-black">{o.number} <span className="font-medium text-slate-500">· {o.productName} × {o.quantity}</span></p><p className="mt-1 text-sm text-slate-600">{o.delivery.city}, {o.delivery.country} · {new Date(o.createdAt).toLocaleString('fr-FR')}</p></div><p className="font-black">{o.total.toLocaleString('fr-FR')} {o.currency}</p><select value={o.status} onChange={e=>change(o.id,e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-extrabold outline-none focus:border-violet">{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></article>)}</div>:<div className="p-12 text-center"><p className="text-xl font-black">Aucune commande pour le moment.</p><p className="mt-2 text-sm text-slate-500">Les commandes de votre boutique apparaîtront ici.</p></div>}</div></>;
}
