'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Product = { id: string; name: string; description: string; price: number; status: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED'; source: string; imageUrl?: string; benefits: string[]; createdAt: string };
type Data = { store: { name: string; slug: string; currency: string } | null; products: Product[]; limit: number | null };
const price = (amount: number, currency: string) => `${Math.round(amount).toLocaleString('fr-FR')} ${currency}`;

export function ProductsClient() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/products').then(async (response) => { const json = await response.json(); if (!response.ok) throw new Error(json.error); return json; }).then(setData).catch((reason) => setError(reason.message)); }, []);
  if (error) return <div className="rounded-2xl bg-red-50 p-5 font-bold text-red-700">{error}</div>;
  if (!data) return <div className="animate-pulse rounded-2xl bg-slate-200 p-16 text-slate-400">Chargement du catalogue…</div>;
  if (!data.store) return <section className="rounded-[2rem] bg-ink p-8 text-white sm:p-12"><p className="text-sm font-black uppercase tracking-[.16em] text-mint">Catalogue Zelvora</p><h1 className="mt-3 text-4xl font-black tracking-[-.055em]">Créez d’abord votre boutique.</h1><p className="mt-4 max-w-xl leading-7 text-slate-300">Une boutique est nécessaire pour que vos produits restent isolés et puissent être publiés.</p><Link href="/onboarding" className="mt-7 inline-block rounded-xl bg-white px-5 py-3 font-extrabold text-ink">Créer ma boutique →</Link></section>;
  const used = data.products.length; const limitLabel = data.limit === null ? 'Produits illimités' : `${used} / ${data.limit} produits utilisés`;
  return <><section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-[.16em] text-violet">Catalogue · {data.store.name}</p><h1 className="mt-2 text-3xl font-black tracking-[-.055em] sm:text-4xl">Vos produits</h1><p className="mt-2 text-slate-600">Ajoutez, analysez et vérifiez chaque produit avant sa diffusion.</p></div><Link href="/analysis" className="rounded-xl bg-violet px-5 py-3.5 text-center font-extrabold text-white shadow-lg shadow-violet/25">+ Ajouter un produit</Link></section><div className="mt-6 flex items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white px-5 py-4"><div><p className="font-black">{limitLabel}</p><p className="mt-1 text-sm text-slate-500">La limite est contrôlée par le serveur selon votre abonnement.</p></div><Link href={`/store/${data.store.slug}`} target="_blank" className="shrink-0 text-sm font-extrabold text-violet">Voir la boutique ↗</Link></div>{data.products.length === 0 ? <section className="mt-7 rounded-[2rem] border border-dashed border-slate-300 bg-white p-10 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-violet/10 text-2xl text-violet">✦</div><h2 className="mt-5 text-2xl font-black">Votre catalogue est prêt.</h2><p className="mx-auto mt-3 max-w-md leading-7 text-slate-600">Importez une image, une URL ou vos propres informations. Zelvora structure les suggestions, que vous gardez toujours sous contrôle.</p><Link href="/analysis" className="mt-6 inline-block rounded-xl bg-violet px-5 py-3 font-extrabold text-white">Lancer l’analyse IA →</Link></section> : <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.products.map((product) => <article key={product.id} className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="grid h-44 place-items-center bg-surface">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} className="h-full w-full object-contain p-4" /> : <span className="text-5xl text-violet">✦</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-black leading-5">{product.name}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-black ${product.status === 'PUBLISHED' ? 'bg-mint/40 text-emerald-800' : 'bg-amber-100 text-amber-800'}`}>{product.status === 'PUBLISHED' ? 'Publié' : 'Brouillon'}</span></div><p className="mt-3 line-clamp-2 text-sm leading-5 text-slate-500">{product.description}</p><div className="mt-4 flex items-center justify-between"><p className="font-black">{price(product.price, data.store!.currency)}</p><p className="text-xs font-bold text-slate-400">Source : {product.source === 'LINK' ? 'URL' : product.source === 'IMAGE' ? 'Image' : 'Manuel'}</p></div></div></article>)}</section>}</>;
}
