create table if not exists public.ad_campaigns(
 id uuid primary key default gen_random_uuid(), partner_name text not null check(char_length(partner_name) between 2 and 120), partner_email text, title text not null check(char_length(title) between 2 and 140), body text not null default '', image_url text not null, destination_url text not null check(destination_url ~ '^https://'), cta text not null default 'Découvrir', monthly_price numeric(12,2) not null check(monthly_price>=0), amount_received numeric(12,2) not null default 0, payment_method text, payment_reference text, payment_status text not null default 'PENDING' check(payment_status in('PENDING','PAID','REJECTED','REFUNDED')), status text not null default 'DRAFT' check(status in('DRAFT','PENDING_REVIEW','SCHEDULED','ACTIVE','SUSPENDED','ENDED','REJECTED')), starts_at timestamptz not null, ends_at timestamptz not null, max_impressions bigint, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(ends_at>starts_at)
);
create table if not exists public.ad_events(id bigint generated always as identity primary key,campaign_id uuid not null references public.ad_campaigns(id) on delete cascade,event_type text not null check(event_type in('IMPRESSION','CLICK')),viewer_hash text not null,created_at timestamptz not null default now());
create index if not exists ad_events_campaign_created_idx on public.ad_events(campaign_id,created_at);
alter table public.ad_campaigns enable row level security;alter table public.ad_events enable row level security;
create policy "admins manage campaigns" on public.ad_campaigns for all using(public.is_platform_admin()) with check(public.is_platform_admin());
create policy "authenticated read active ads" on public.ad_campaigns for select to authenticated using(payment_status='PAID' and status='ACTIVE' and now() between starts_at and ends_at);
create policy "admins read ad events" on public.ad_events for select using(public.is_platform_admin());
create or replace function public.record_ad_event(p_campaign_id uuid,p_event_type text,p_viewer_hash text) returns void language plpgsql security definer set search_path=public as $$ begin if p_event_type not in('IMPRESSION','CLICK') then raise exception 'Invalid event';end if;if not exists(select 1 from ad_campaigns where id=p_campaign_id and payment_status='PAID' and status='ACTIVE' and now() between starts_at and ends_at)then raise exception 'Campaign inactive';end if;if p_event_type='IMPRESSION' and exists(select 1 from ad_events where campaign_id=p_campaign_id and event_type='IMPRESSION' and viewer_hash=p_viewer_hash and created_at>now()-interval '1 day')then return;end if;insert into ad_events(campaign_id,event_type,viewer_hash)values(p_campaign_id,p_event_type,left(p_viewer_hash,128));end;$$;
grant execute on function public.record_ad_event(uuid,text,text) to authenticated;
notify pgrst,'reload schema';
