import { NextRequest } from 'next/server';
import { z } from 'zod';
import { currentUser } from '@/lib/auth';
import { mutateDb, readDb } from '@/lib/db';
import { apiError, assertSameOrigin } from '@/lib/security';
import { clientFor, fail, mapOrder, storeForUser } from '@/lib/supabase/data';
import { useSupabase } from '@/lib/supabase/config';
const statusSchema = z.enum(['NEW', 'CONFIRMED', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED']);
async function ownedStore(userId: string) { const db = await readDb(); const org = db.organizations.find((item) => item.userId === userId); return { db, store: org ? db.stores.find((item) => item.organizationId === org.id) : undefined }; }
export async function GET() { const user = await currentUser(); if (!user) return Response.json({ error: 'Utilisateur non authentifié.' }, { status: 401 }); if (useSupabase && user.accessToken) { const { store } = await storeForUser({ ...user, accessToken: user.accessToken }); if (!store) return Response.json({ orders: [] }); const { data, error } = await clientFor(user).from('orders').select('*').eq('store_id', store.id).order('created_at', { ascending: false }); if (error) fail(error); return Response.json({ orders: (data || []).map(mapOrder) }); } const { db, store } = await ownedStore(user.id); if (!store) return Response.json({ orders: [] }); return Response.json({ orders: db.orders.filter((item) => item.storeId === store.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt)) }); }
export async function PATCH(request: NextRequest) { try { assertSameOrigin(request); const user = await currentUser(); if (!user) throw new Error('Utilisateur non authentifié.'); const body = z.object({ id: z.string().uuid(), status: statusSchema }).parse(await request.json()); if (useSupabase && user.accessToken) { const { data, error } = await clientFor(user).from('orders').update({ status: body.status }).eq('id', body.id).select('*').single(); if (error) fail(error, 'Commande introuvable ou non autorisée.'); return Response.json({ order: mapOrder(data) }); } const updated = await mutateDb((db) => { const org = db.organizations.find((item) => item.userId === user.id); const store = org && db.stores.find((item) => item.organizationId === org.id); const order = db.orders.find((item) => item.id === body.id && item.storeId === store?.id); if (!order) throw new Error('Commande introuvable ou non autorisée.'); order.status = body.status; return order; }); return Response.json({ order: updated }); } catch (error) { return apiError(error); } }
