import { NextRequest } from 'next/server';
import { z } from 'zod';
import { id, mutateDb, now } from '@/lib/db';
import { apiError, assertSameOrigin, rateLimit } from '@/lib/security';
import { createSupabasePublicClient } from '@/lib/supabase/server';
import { fail } from '@/lib/supabase/data';
import { useSupabase } from '@/lib/supabase/config';
const bodySchema = z.object({ storeSlug: z.string().min(1).max(80), productId: z.string().uuid(), quantity: z.number().int().min(1).max(20).default(1), name: z.string().trim().min(2).max(100), phone: z.string().trim().min(6).max(32), whatsapp: z.string().trim().max(32).optional(), email: z.string().email().max(254).optional().or(z.literal('')), country: z.string().trim().min(2).max(56), city: z.string().trim().min(2).max(80), district: z.string().trim().max(80).optional(), address: z.string().trim().max(200).optional(), notes: z.string().trim().max(500).optional() });
export async function POST(request: NextRequest) {
  try {
    assertSameOrigin(request); rateLimit(request, 'public-order', 8); const input = bodySchema.parse(await request.json());
    if (useSupabase) { const { data, error } = await createSupabasePublicClient().rpc('create_public_order', { p_store_slug: input.storeSlug, p_product_id: input.productId, p_quantity: input.quantity, p_name: input.name, p_phone: input.phone, p_whatsapp: input.whatsapp || null, p_email: input.email || null, p_country: input.country, p_city: input.city, p_district: input.district || null, p_address: input.address || null, p_notes: input.notes || null }); if (error) fail(error, 'Impossible d’enregistrer la commande.'); const order = Array.isArray(data) ? data[0] : data; if (!order) throw new Error('La commande n’a pas été créée.'); return Response.json({ order: { number: order.order_number, total: Number(order.total), currency: order.currency } }, { status: 201 }); }
    const order = await mutateDb((db) => { const store = db.stores.find((item) => item.slug === input.storeSlug && item.status === 'PUBLISHED'); if (!store) throw new Error('Cette boutique n’est pas disponible.'); const product = db.products.find((item) => item.id === input.productId && item.storeId === store.id && item.status === 'PUBLISHED'); if (!product) throw new Error('Ce produit n’est plus disponible.'); const timestamp = now(); let customer = db.customers.find((item) => item.storeId === store.id && item.phone === input.phone); const total = product.price * input.quantity; if (customer) { customer.name = input.name; customer.whatsapp = input.whatsapp || customer.whatsapp; customer.email = input.email || customer.email; customer.orderCount += 1; customer.totalSpent += total; customer.lastOrderAt = timestamp; } else { customer = { id: id(), storeId: store.id, name: input.name, phone: input.phone, whatsapp: input.whatsapp, email: input.email || undefined, orderCount: 1, totalSpent: total, lastOrderAt: timestamp, createdAt: timestamp }; db.customers.push(customer); } const created = { id: id(), storeId: store.id, customerId: customer.id, number: `ZV-${String(db.orders.filter((item) => item.storeId === store.id).length + 1).padStart(4, '0')}`, status: 'NEW' as const, paymentStatus: 'PENDING' as const, paymentMethod: 'CASH_ON_DELIVERY' as const, currency: store.currency, total, quantity: input.quantity, productId: product.id, productName: product.name, delivery: { country: input.country, city: input.city, district: input.district, address: input.address, notes: input.notes }, createdAt: timestamp }; db.orders.push(created); db.notifications.push({ id: id(), storeId: store.id, userId: store.ownerId, title: 'Nouvelle commande reçue', body: `${created.number} · ${input.name} · ${total.toLocaleString('fr-FR')} ${store.currency}`, read: false, createdAt: timestamp }); return created; }); return Response.json({ order: { number: order.number, total: order.total, currency: order.currency } }, { status: 201 });
  } catch (error) { return apiError(error); }
}
